#! /usr/bin/env python
# -*- coding: utf-8 -*-
import sys, codecs, os
import datetime

from el_t01_app.models import Profile
from el_t01_app.models import Game_history
from el_t01_app.models import Ticket_history

m_zvit_date_start_db = datetime.datetime(2022,12,19)
m_zvit_date_finish_db = datetime.datetime(2023,2,8)

m_bloger_id = 35

m_list_user = [
    "yz6318@gmail.com",
    "meital.shua@gmail.com",
    "atik5484@gmail.com",
    "shervaba51@gmail.com",
    "7660311@gmail.com",
    "tomersheri@gmail.com",
    "hilelgo@neveshmuel.org.il",
    "aviadtsarfati@gmail.com",
    "ziofer1@gmail.com",
    "pinhasov.adv@gmail.com",
    "ron@ronack.org",
    "izcnisim@gmail.com",
    "anteradam1977@gmail.com",
    "lslyrhl@gmail.com",
    "shlomiavital0011@gmail.com",
    "orli9872@gmail.com",
    "go_home@walla.com",
    "watn.phone2019@hotmail.com",
    "ichielfisher@gmail.com",
    "aviycook@gmail.com",
    "navatol@gmail.com",
    "shimon.danon49@gmail.com",
    "argisasi@gmail.com",
    "shahar5591@gmail.com",
    "boazcohen1962@gmail.com",
    "mikyp124@gmail.com",
    "orlinger@gmil.com",
    "ozmiz2001@gmail.com",
    "noam529@gmail.com",
    "love3yasmin@gmail.com",
    "dudibhp@gmail.com",
    "maya@pitaro.info",
    "yaniv1747@gmail.com",
    "henoni@walla.com",
    "adicohen365@gmail.com",
    "meshyrahamim@gmail.com",
    "david0527166@gmail.com",
    "idanmizrahi1990@gmail.com",
    "amiram.hazan@gmail.com",
    "mirabo58@gmail.com",
    "kobizagar12@gmail.com",
    "israelimalka5@gmail.com",
    "dglssb131122@gmail.com",
    "yoelya31@gmail.com",
    "bnayagol@gmail.com",
    "limorbem@gmail.com",
    "multi-systems@outlook.com",
    "shirlyxxd@gmail.com",
    "mcn.moni@gmail.com",
    "king1swimmer@gmail.com",
    "kartzman885@gmail.com",
    "alex227@zahav.net.il",
    "m.7aj91@gmail.com",
    "renne04@gmail.com",
    "0542666584a@gmail.com",
    "yariv.hen1@gmail.com",
    "aroch2@walla.co.il",
    "rg140771@gmail.com",
    "habtamogdamo123@gmail.com",
    "boaz438@gmail.com",
    "yaron1601@gmail.com",
    "srayaru@gmail.com",
    "erelit@gmail.com",
    "s_hamood@walla.co.il",
    "yisca.barad@gmail.com",
    "klr352@gmail.com",
    "williamscucu@gmail.com",
    "carmit3232@gmail.com",
    "helenakenizo103@103gmail.com",
    "nisim150468@gmail.com",
    "sshirr23@gmail.com",
    "hagaykl@gmail.com",
    "itay1975@gmail.com",
    "kobi.museum@gmail.com",
    "veredalon31@gmail.com",
    "albertmalka86@gmail.com",
    "yardenszabo@gmail.com",
    "guy@writeguy.co.il",
    "avrahamgton@gmail.com",
    "spyhaz@walla.com",
    "mazi.mazuz@gmail.com",
    "salzburg1982@gmail.com",
    "waseemhmamde@gmail.com",
    "asulinav@gmail.com",
    "oshrat.tandoh41@gmail.com",
    "aee85669@gmail.com",
    "nagosegil@gmail.com",
    "o.flaysher@gmail.com",
    "efis@elad.muni.il",
    "yamen27@walla.com",
    "sagiab19@gmail.com",
    "grossmandrey@gmail.com",
    "hadas2112@gmail.com",
    "sebagsebag@gmail.com",
    "meidanko@gmail.com",
    "salemkit@hotmail.com",
    "eliyahumalayev2003@gmail.com",
    "roeyavneem5@gmail.com",
    "isaacsandman@walla.co.il",
    "ovadyaadir@gmail.com",
    "ohad313162992@gmail.com",
    "myrydql4@gmail.com",
    "hezki507@gmail.com",
    "arevi1987@gmail.com",
    "yshlain1@gmail.com",
    "adeebghol4@gmail.com",
    "sheky4171@gmail.comcom",
    "avishai5460@g.mail.com",
    "sivic4@walla.com",
    "6284548@gmail.com",
    "roman.perelman@gmail.com",
    "nagareli@gmail.com",
    "aviranwais7@gmail.com",
    "izhackya@gmail.com",
    "or_chama@walla.com",
    "edensamazon1m@gmail.com",
    "bitaoavi@gmail.com",
    "hirshshere5@gmail.com",
    "yhwdhmtw7@gmail.com",
    "georginakaa@gmail.com",
    "lalikr60@gmail.com",
    "sh8517843@gmail.com",
    "yaelt@1982wall.com",
    "hddryh752@gmail.com",
    "dror6478@gmail.com",
    "yonihirshbain@gmail.com",
    "noa.alfiacohen1@gmail.com",
    "israelallali20@gmail.com",
    "yosefboronshtein@gmail.com",
    "danny747@bezeqint.net",
    "tbrrcp@gmail.com",
    "kifah.ayoub@gmail.com",
    "eliaszada@gmail.com",
    "mark.zismanovich@gmail.com",
    "doriansarussi054@gmail.com",
    "sirakovich@gmail.com",
    "sagiokev5@gmail.com",
    "yaelstp@gmail.com",
    "meir0549463644@gmail.com",
    "moshe.levantovsky@intel.com",
    "aryehhju@gmail.com",
    "0606adw@gmail.com",
    "moses8017@gmail.com",
    "eyal739@gmail.com",
    "goset316@gmail.com",
    "hb0547225203@gmail.com",
    "asteramos95@gmail.com",
    "roni.office.law@gmail.com",
    "yarinbarel04@gmail.com",
    "shimikdoshim@icloud.com",
    "aviv858511@gmail.com",
    "brachab55@gmail.com",
    "aassaf3031@gmail.com",
    "ornacyi@gmail.com",
    "a0533168678@gmail.com",
    "esub053@gmail.com",
    "hilladayan@walla.co.il",
    "hhn36956@gmail.com",
    "bikov83@gmail.com",
    "elisharonnatali@gmail.com",
    "richitcha@gmail.com",
    "dudu29sabag@gmail.com",
    "zivhy1950@gmail.com",
    "a0587122651@gmail.com",
    "alexxcr8@gmail.com",
    "dwdprz52@gmail.com",
    "sher2905@gmail.com",
    "braonokbada@gmail.com",
    "idanhartal@gmail.com",
    "talya15951@gmail.com",
    "eventovro@hotmail.com",
    "yoelavidani@gmail.com",
    "origamliel@walla.com",
    "abiiloz1234@gmail.com",
    "m.1983.123@hotmeil.com",
    "alan.sirhan@gmail.com",
    "ornaraviz@gmail.com",
    "magen67519@gmail.com",
    "michilis119@gmail.com",
    "zidan339@gmail.com",
    "nzrmgdy1@gmail.com",
    "miko429@ymail.com",
    "ronit.e71@gmail.com",
    "katiakofman@gmail.com",
    "fishelberk2008@gmail.com",
    "ronit217@gmail.com",
    "riwaida-s@hotmail.com",
    "zipishmueli@gmail.com",
    "bolotov540@gmail.com",
    "lizakeinan@icloud.com",
    "yossiy07@gmail.com",
    "moaad@zahav.net.il",
    "moticohen46@icloud.com",
    "hnyqwzly@gmail.com",
    "hdshds650@gmail.xom",
    "shoam05452@gmail.com",
    "s533157484@gmail.com",
    "oshratparvi@walla.com",
    "amitw6928@gmail.com",
    "noneta_12@hotmail.com",
    "lika49@walla.co.il",
    "avyocohen@gmail.com",
]


blogger_users = Profile.objects.filter(settings__ref_blogger_id=m_bloger_id).filter(
    date_joined__range=[m_zvit_date_start_db, m_zvit_date_finish_db])

m_all_user = 0
m_user_d = 0
m_user_n = 0

for index_item, item in enumerate(blogger_users):
    m_all_user += 1
    if item.user.email in m_list_user:
        m_user_d += 1
    else:
        print ("11 =", item.settings)
        m_mm = item.settings
        m_mm["get_param"].pop("utm_campaign", {})
        m_mm.pop("ref_blogger_id", {})
        item.settings = m_mm
        item.save()
        print("22 =", item.settings)
        m_user_n += 1


print ('m_all_user = ', m_all_user)
print ('m_user_d   = ', m_user_d)
print ('m_user_n   = ', m_user_n)
