# Generated by Django 3.2.8 on 2023-09-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_t01_app', '0002_auto_20230925_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_history',
            name='shop_code1',
        ),
    ]
