# Generated by Django 3.2.8 on 2023-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_t01_app', '0003_remove_game_history_shop_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_external_company',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
