# Generated by Django 3.2.8 on 2023-02-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('add_param', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MessengerType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verbal', models.CharField(max_length=50, verbose_name='Verbal code')),
                ('caption', models.CharField(max_length=50, verbose_name='Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verbal', models.CharField(max_length=50, verbose_name='Verbal code')),
                ('caption', models.CharField(max_length=150, verbose_name='Caption')),
                ('settings', models.JSONField(default=dict)),
                ('messenger_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messengers', to='bot_message_app.messengertype', verbose_name='Messenger type')),
            ],
        ),
    ]
